### ISSUE TITLE
fields displayed for updates

### ISSUE THREAD

**Issue by gpinkham** [agardiner/csv-diff-report#1]
is there a way to get ALL fields of the row to show in the Excel file for an update?     I really can't figure out the pattern to what fields show up by some of my key fields don't show and it makes it nearly impossible to find the row in the original source (this is because some of the files have dupes and the diff ignores dupe rows so the row field in the output isn't accurate.. at least that's what I'm thinking is causing the row number to be wrong)..  at any rate..   having the fields there in the diff would be a huge win for me.  I spend a ton of time tracking down the data in the source files..   

thanks
Gary

**Comment by agardiner** [comment]
Not at present. 

Just so that I'm clear on what you want - do you want only rows with differences to be included in Excel, but for those rows, you'd like to see _all_ values (including those of fields with no differences)?

BTW If you are getting duplicates in your data, your diffs won't be accurate. If a duplicate key is found, the duplicate is ignored - so it is really key to be able to uniquely identify every row.

**Comment by agardiner** [comment]
Added the --include-matched flag to provide the ability to include all field values for lines that differ in b4269e837fc64c888fd4403a412183508dc30ce3.
