### ISSUE TITLE
Save diff as Text

### ISSUE THREAD

**Issue by broex** [agardiner/csv-diff-report#3]
Hello,
I'm trying to save a diff as a text file, but I'm getting a lot of errors.
I've copied my input in het terminal and the corresponding result:

ruby /users/broex/.rvm/gems/ruby-2.2.1/bin/csvdiff prod.csv new.csv --parent-fields data_uri --child-fields data_uri --format text
Performing file diff:
  From File:    prod.csv
  To File:      new.csv
Opening FROM file 'prod.csv'...  43907 lines read
Opening TO file 'new.csv'...  43907 lines read
Found 43907 differences: 43907 Updates
/Users/broex/.rvm/gems/ruby-2.2.1/gems/csv-diff-report-0.3.1/lib/csv-diff-report/text.rb:31:in `text_diff': undefined local variable or method`csv' for #CSVDiff::Report:0x007f8e71a1e350 (NameError)
    from /Users/broex/.rvm/gems/ruby-2.2.1/gems/csv-diff-report-0.3.1/lib/csv-diff-report/text.rb:17:in `block (2 levels) in text_output'
    from /Users/broex/.rvm/gems/ruby-2.2.1/gems/csv-diff-report-0.3.1/lib/csv-diff-report/text.rb:16:in`each'
    from /Users/broex/.rvm/gems/ruby-2.2.1/gems/csv-diff-report-0.3.1/lib/csv-diff-report/text.rb:16:in `block in text_output'
    from /users/broex/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1273:in`open'
    from /Users/broex/.rvm/gems/ruby-2.2.1/gems/csv-diff-report-0.3.1/lib/csv-diff-report/text.rb:15:in `text_output'
    from /Users/broex/.rvm/gems/ruby-2.2.1/gems/csv-diff-report-0.3.1/lib/csv-diff-report/report.rb:121:in`output'
    from /Users/broex/.rvm/gems/ruby-2.2.1/gems/csv-diff-report-0.3.1/lib/csv-diff-report/cli.rb:116:in `process'
    from /Users/broex/.rvm/gems/ruby-2.2.1/gems/csv-diff-report-0.3.1/lib/csv-diff-report/cli.rb:78:in`run'
    from /Users/broex/.rvm/gems/ruby-2.2.1/gems/csv-diff-report-0.3.1/bin/csvdiff:7:in `<top (required)>'
    from /users/broex/.rvm/gems/ruby-2.2.1/bin/csvdiff:23:in`load'
    from /users/broex/.rvm/gems/ruby-2.2.1/bin/csvdiff:23:in `<main>'

**Comment by agardiner** [comment]
Well, that's a little embarrassing - there was a very obvious bug in the text output routine that I really should have picked up. I've fixed it now in aee3a66, and also pushed updates of the csv-diff and csv-diff-report gems to rubygems.org.

Also, in your test case above, you can use the --key-fields option instead of the --parent-fields and --child-fields option, i.e.
    csvdiff prod.csv new.csv --key-fields data_uri --format text

You shouldn't specify the same field as both a parent and a child - they each need to be unique. If you have just one key field, or there is no hierarchical relationship in your data, you should just use --key-fields instead.

Thanks for finding and reporting this issue!

**Comment by broex** [comment]
Thanks it's working now!
The reason i'm using the parent and child fields is because it's a lot faster.
I haven't been able to complete a diff when using the keyfield option.
The process seems to take a long time with comparing the files

**Comment by agardiner** [comment]
OK - glad its working.
I am a little concerned that you might not be getting correct results using --parent-fields and --child-fields with the same field name. Its definitely not a case I considered, and there's every possibility this could give you incorrect results. What happens if you try using just --child-fields?

**Comment by broex** [comment]
So far it seemed to give the right result, but i will do a more thorough to check if this is correct.
Using both fields as child-field seems to give the same result, the script has been running for around an hour and is still at comparing the records.
