### ISSUE TITLE
It does not work if csv file name is specified as an absolute path.

### ISSUE THREAD

**Issue by maeken2010** [agardiner/csv-diff-report#8]
Hello.
I'm trying to generate csv diff report as html.
But, when csv file path is absolute, it does not work.
it just works by specifying the csv file as a relative path.

```
$ csvdiff test.csv test_old.csv
/Library/Ruby/Gems/2.0.0/gems/arg-parser-0.3.0/lib/arg-parser/dsl.rb:70: warning: instance variable @arg_opts not initialized
Performing file diff:
  From File:    test.csv
  To File:      test_old.csv
Opening FROM file 'test.csv'...  3 lines read
Opening TO file 'test_old.csv'...  3 lines read
Found 1 differences: 1 Updates
Diff report saved to './Diff_test_to_test_old.html'
```

```
$ csvdiff /Users/maeken/csv/test.csv /Users/maeken/csv/test_old.csv
/Library/Ruby/Gems/2.0.0/gems/arg-parser-0.3.0/lib/arg-parser/dsl.rb:70: warning: instance variable @arg_opts not initialized

USAGE: ruby /usr/local/bin/csvdiff FROM TO [PATTERN] [OPTIONS]

Specify the /? or --help option for more detailed help
```

**Comment by agardiner** [comment]
Hi,

Thanks for finding this - it seems it was a longstanding bug in another gem of mine called arg-parser that was the problem. I guess I must always use relative paths, since I'd not come across this issue before. :-)

In any case, I've fixed the bug and pushed an update to the arg-parser gem, which is now at version 0.3.1. If you update that gem, it should resolve this issue for you.

Cheers!

**Comment by maeken2010** [comment]
Thanks for your support :D
