### ISSUE TITLE
show only changed fields in diff report

### ISSUE THREAD

**Issue by willywutang** [agardiner/csv-diff-report#9]
It can be useful to show only the fields that have been changed when comparing two CSVs.
Currently the rows are filtered this way, but the columns are not. 
Apologies in advance if the tool already has options to support this but I am not seeing it.

**Comment by aldefouw** [comment]
@willywutang - I had the same need for a project I am working on because it had over 6,000 columns of data and it was too much to sift through.

Thus, I made a fork of the project and re-coded part of the HTML module with the change you requested above.

In the fork, I'm only returning columns where changes are present in some row. 

https://github.com/aldefouw/csv-diff-report

I additionally ignore trailing and leading whitespace errors in my fork.  (If you don't want that, you can checkout commit 39b743b on my fork, which did not yet ignore trailing and leading whitespace.)

This is a quick and dirty modification to the script;  however, I'm sure that it could be made into an official implementation with some work.  

I did not bother making this a CLI switch you turn on and off.  I don't have a use for it with my implementation.  But if you feel that you do, you can feel free to fork from mine and implement.  (Or the original author if he so chooses ... )

Enjoy.

**Comment by willywutang** [comment]
@aldefouw Awesome! It is funny, we were discussing programming this just today and you beat us to it. This is very helpful, thanks so much!

**Comment by aldefouw** [comment]
@willywutang  - Ha!  That's great.

I just needed to get this done before a data transfer next week so I decided to take an hour this morning and dig into it.  It wasn't too bad once I understood how things were being handled.

**Comment by willywutang** [comment]
@aldefouw Your fork crashes for me on many diffs, with the following error:

/usr/local/lib/ruby/gems/2.4.0/gems/csv-diff-report-0.3.5/lib/csv-diff-report/html.rb:191:in `include_column?': undefined method `include?' for nil:NilClass (NoMethodError)

**Comment by aldefouw** [comment]
@willywutang - Sounds like I missed putting a guard on something - my example data never encountered that.  I'll look into it tomorrow if I have time, but I plan to do a huge data transfer tomorrow.

Do you have an example data set that reproduces the error so I can verify it will work for you if I have time to fix?

Ordinarily I test my code with rspec tests, but I've been too swamped to do that on this project unfortunately.  This was a hasty fork that was thrown together really.

**Comment by aldefouw** [comment]
@willywutang - I added a guard to the line that was giving you a nil error.  

Try pulling my fork and see if it works for you now.

**Comment by aldefouw** [comment]
Any luck with the newest version of my fork, @willywutang ?

**Comment by willywutang** [comment]
Hi @aldefouw! Thanks for looking into this, I tried your latest version, but I got the same errors. It occurs with some CSVs but not with others. Unfortunately I'm not able to make an example dataset quickly for you because the contents are sensitive.

**Comment by aldefouw** [comment]
@willywutang - My dataset contains protected information - so I completely understand the discretion.

What's your Ruby version you're running in?  Environment?

Is it possible to post a full stack trace?

By the way, when I am running my csv-diff, this is the command line I am issuing the following:
`csvdiff data1.csv data2.csv --key-fields 0,1 --format html`

Is that along the lines of how you are running this script?  

Also, I bumped the version to 0.3.6 in case it didn't pull the latest version of the fork for you ...

**Comment by willywutang** [comment]
Hi @aldefouw it seems to be working properly now, after I reinstalled from the latest 0.3.6 version. I thought I had made sure to use 0.3.5, but maybe my gem uninstall / reinstall procedure was somehow bugged. Thanks so much!
